import Head from 'next/head'
import classes from '@/styles/Home.module.css'
import Link from 'next/link';
import Hero from '../comps/Hero.js';
import TechScroll from '../comps/TechScroll.js';
import AboutMe from '../comps/AboutMe.js';
import MyWork from '../comps/MyWork.js';


export default function Home() {
  return (
    <>
      <Head>
        <title>Evan's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={classes.bigNav}>
        <h1 className={classes.logo}>evanoshea.dev</h1>
        <div className={classes.links}>
          <Link className={classes.link}  href='www.google.com'>my work</Link>
          <Link className={classes.link}  href='www.google.com'>contact</Link>
        </div>
      </div>

      <Hero />
      <TechScroll />
      <AboutMe />
      <MyWork />

    </>
  )
}
